[options]
admin_passwd = $pbkdf2-sha512$600000$Z6y1dk6ptTaG8P6fc07JmQ$iaYhS2LMyN/cXIjBKYafmXGN2ZmFCFy/ddJ.XhRdzJA56RP0tmGeZXk6ZxnVEQ.YnI0uglTPykGh8z05M60ueA
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = C:\projects\inspection-portal\odoo-17\addons, C:\projects\inspection-portal\odoo-17\addons\qss_portal
wkhtmltopdf = C:\projects\inspection-portal\odoo-17\wkhtmltopdf.exe